### PR TITLE
Update submodules and to work with emacs v27

### PR DESCRIPTION
**Pull request by josephfosco**
This pull request updates emacs-live to work with emacs v27.
All submodules have been updated
Removed popwin module - it is causing trouble and non-trivial to fix. In addition it appears it is no longer maintained.
hydra was also removed - there was also some issue with this. I do not remember the details.

Several new files that were needed due to submodule updates have been added

There is still an issue with the erlang lang-pack. It seems there is/was a link to tags.erl. This should link to ../src/tags.erl. the linked to file is missing. I am not certain how to fix this. Also, not being an erlang programmer, I am not certain how to test any attempts I make to fix this

### CODE REVIEW

**Comment by samaaron** [comment]
hi there, this looks really great, thanks very much - but please could you modify the dev packs not stable, the stable is there for releases (which I'll do as soon as I get things working at my end).

**Comment by josephfosco** [comment]
> hi there, this looks really great, thanks very much - but please could you modify the dev packs not stable, the stable is there for releases (which I'll do as soon as I get things working at my end).

Thanks for looking at this. I originally updated the dev packs (via submodules) but then ran emacs-live/packs/update-live-packs. I will put the stable packs back, and just leave the dev updates in the PR. It might take a day or 2 to get to this. Thanks again!

**Comment by josephfosco** [comment]
Updated packs in dev and restored stable to current release  Some of the files in stable are showing up as having changes, however every file I checked (in stable/) does match what is currently in overtone/emacs-live. If you think this is going to cause a problem, please let me know and I'll look into it further - If necessary, I can close this PR and create a separate new one that I think will not list these as changes.

**Comment by samaaron** [comment]
@josephfosco - looks like there's a bunch of conflicts. Perhaps it might be easier to close and create a new PR? Sorry for the faff!

**Comment by josephfosco** [comment]
@samaaron No Problem. I was thinking that might be a better idea. I will get a new PR up today or tomorrow. Thanks.

**Comment by josephfosco** [comment]
@samaaron After working on my fork all the conflicts are resolved and this now looks like a much more reasonable PR to me. Please take a look and let me know if you see any further issues. Thanks for looking at this.

**Comment by samaaron** [comment]
Awesome, thank-you so much for this :-)

**Pull request merged**
