### PR TITLE
Remove Invalid Symlink File

### PR DESCRIPTION
**Pull request by femnad**
This pull request removes an invalid symlink to the `CHANGELOG.md` file.

### CODE REVIEW

**Comment by samaaron** [comment]
Actually I think you can remove that entire tmp file :)

**Comment by femnad** [comment]
I thought I did that, I am missing anything? Also do you think that pattern (files starting with .#) should be added to the `.gitignore` file?

**Comment by samaaron** [comment]
Ah yes, my mistake - just looked like you removed a line first time I glanced. Also, yes I think `.#` should be added to `.gitignore` :-)

**Comment by samaaron** [comment]
Also, thanks for this commit!

**Comment by femnad** [comment]
Sure thing. The way GitHub displayed the diff confused me too.

**Pull request merged**
